# Dockerfile for building server image

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install the dependencies
RUN apt-get update && apt-get install -y \
    python3-dev \
    zlib1g-dev \
    gcc make \
    libmariadb-dev \
    pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container at /app
COPY ./requirements.txt /app/requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the all files
COPY . .

# Expose the necessary port to use by user frontend
EXPOSE 5000

# Set the default command
CMD ["python", "-m", "app"]
