# Dockerfile for building front-end image for admin dashboard
FROM node:current-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port 5173
EXPOSE 5173

# Set the default command
CMD ["npm", "run", "dev"]
